allowBuilds:
  playwright-chromium: true
  esbuild: true
minimumReleaseAgeExclude:
  - '@slidev/cli@52.19.1'
  - '@slidev/client@52.19.1'
  - '@slidev/parser@52.19.1'
  - '@slidev/types@52.19.1'
  - slidev-theme-alchemmist@0.3.0 || 0.3.1
